import tkinter, vlajkamodul
canvas = tkinter.Canvas(height = 800, width = 1200)
canvas.pack()

subor = open('rozloha.txt', 'r')
krajiny, rozlohy, obyvatelia, hdp = [], [], [], []
for riadok in subor:
    dvojbodka = riadok.find(':')
    ciarka = riadok.find(',')
    ciarka_2 = riadok.rfind(',')
    krajiny.append(riadok[:dvojbodka])
    rozlohy.append(riadok[dvojbodka + 1:ciarka])
    obyvatelia.append((riadok[ciarka + 1:ciarka_2]))
    hdp.append((riadok[ciarka_2 + 1:]).strip())

print(krajiny)
print(rozlohy)
def rozloha():
    taliansko.zoom(int(rozlohy[0]) / 1000000)
    taliansko.kresli(canvas)
    canvas.update()
    francuzko.zoom(int(rozlohy[1]) / 1000000)
    francuzko.kresli(canvas)
    canvas.update()
    polsko.zoom(int(rozlohy[2]) / 1000000)
    polsko.kresli(canvas)
    canvas.update()
    nemecko.zoom(int(rozlohy[3]) / 1000000)
    nemecko.kresli(canvas)
    canvas.update()

def obyv():
    taliansko.zoom(int(obyvatelia[0]) / 100)
    taliansko.kresli(canvas)
    canvas.update()
    francuzko.zoom(int(obyvatelia[1]) / 100)
    francuzko.kresli(canvas)
    canvas.update()
    polsko.zoom(int(obyvatelia[2]) / 100)
    polsko.kresli(canvas)
    canvas.update()
    nemecko.zoom(int(obyvatelia[3]) / 100)
    nemecko.kresli(canvas)
    canvas.update()

def hdp_velkost():
    taliansko.zoom(int(hdp[0]) / 100000)
    taliansko.kresli(canvas)
    canvas.update()
    francuzko.zoom(int(hdp[1]) / 100000)
    francuzko.kresli(canvas)
    canvas.update()
    polsko.zoom(int(hdp[2]) / 100000)
    polsko.kresli(canvas)
    canvas.update()
    nemecko.zoom(int(hdp[3]) / 100000)
    nemecko.kresli(canvas)
    canvas.update()

vlajka = vlajkamodul.Vlajka
taliansko = vlajka(100, 100, 200, 200, True, ('green', 'white', 'red'))
taliansko.kresli(canvas)
francuzko = vlajka(600, 100, 200, 200, True, ('blue', 'white', 'red'))
francuzko.kresli(canvas)
polsko = vlajka(100, 500, 200, 200, False, ('white','red'))
polsko.kresli(canvas)
nemecko = vlajka(600, 500, 200, 200, False, ('black', 'red', 'yellow'))
nemecko.kresli(canvas)

button_rozloha = tkinter.Button(text = 'Rozloha', command = rozloha)
button_rozloha.pack()
button_obyv = tkinter.Button(text = 'Obyvatelia', command = obyv)
button_obyv.pack()
button_hdp = tkinter.Button(text = 'HDP', command = hdp_velkost)
button_hdp.pack()
canvas.mainloop()